# Generated by Django 2.0.3 on 2018-03-25 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_Id', models.IntegerField()),
                ('sender_number', models.IntegerField()),
                ('receiver_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField(default=datetime.date(2018, 3, 25))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('product', models.TextField()),
            ],
        ),
    ]
